apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: busybox:latest # Use a simple image like BusyBox for testing
      command: ["sh", "-c", "sleep 3600"] # Keep the container running for testing purposes
